_target_: torch.utils.data.DataLoader
batch_size: 1
shuffle: false       # NO shuffle for eval/test
num_workers: 1
pin_memory: true
drop_last: false     # DON'T drop last batch for eval (want all data)
persistent_workers: false
prefetch_factor: 1